language: python
python:
  - '3.5'
  - '3.6'

install:
  - pip install django coverage coveralls

before_script:
  - python manage.py migrate

script:
  - coverage run --branch --source="./hero" manage.py test

after_success: coveralls
